### nodeJs
GET http://localhost:3001/fibonacci

### bunJS
GET http://localhost:3002/fibonacci

### Go
GET http://localhost:3003/fibonacci

### .NET Core 3
GET http://localhost:3004/fibonacci

### .NET Core 8
GET http://localhost:3006/fibonacci
